language: python
python: 2.7
env:
  - WINEENV=py26
  - WINEENV=py27
  - WINEENV=py33
  - WINEENV=py34
  - WINEENV=pypy
before_install:
  - git clone https://github.com/WineAsCI/python-lib-template.git
  - python-lib-template/.travis-setup.sh
install:
    - ./_pip install mako jinja2 cherrypy diesel eventlet gevent gunicorn paste rocket tornado twisted
script: cd bottle && ../_python test/testall.py
